//! Empirical calibration constants — **per content class**.
//!
//! The tables in `calib_tables.rs` are AUTO-GENERATED by
//! `zwr-calibrate/fit_calibration.py` from a disciplined multi-class,
//! multi-size sweep (`benchmarks/calibration_2026-05-28.md`): 4 content
//! classes (photo / screen / line-art / mixed), size variants
//! (tiny/small/medium/native, Mitchell-resampled, downscale-only), synthetic
//! sources at q20–100 step 2, swept against a raw explicit reencode-q grid,
//! each cell the mean over refs/sizes of `(output_len/source_len,
//! cumulative_zensim_a vs the lossless original)`.
//!
//! **Keyed on effective source quality, NOT the header quantizer.** Header
//! detection is unreliable for segmented WebP (see `docs/QUALITY_DETECTION.md`);
//! the router supplies a decode-based estimate (`src/estimate.rs`) as the
//! lookup key. The tables are fit on the TRUE encode quality (so every anchor
//! 30..90 is populated); the runtime decode-based estimate is biased ~−5 vs
//! true q, but est-vs-true keying was measured equivalent (<0.5 cumulative
//! MAE) — interpolation over the anchors absorbs the bias.
//!
//! Cumulative is bounded by the source's own quality: re-encoding cannot make
//! an image closer to the original than the source already is.

use crate::source::ContentClass;

// ---- AUTO-GENERATED tables: SOURCE_Q_ANCHORS, TARGET_Q_GRID,
// {PHOTO,SCREEN,LINEART,MIXED}_{RATIO,CUM,SOURCE_CUM} ----
include!("calib_tables.rs");

const N_ANCHOR: usize = 7;
const N_TARGET: usize = 16;

/// VP8L (lossless re-encode) size ratio for photo content (balloons).
/// Screen / line-art shrinks instead (handled in the projection).
pub const VP8L_PHOTO_RATIO: f32 = 5.0;

/// Per-class table bundle.
struct ClassCalib {
    ratio: &'static [[f32; N_TARGET]; N_ANCHOR],
    cum: &'static [[f32; N_TARGET]; N_ANCHOR],
    source_cum: (f32, f32),
}

fn calib(class: ContentClass) -> ClassCalib {
    match class {
        ContentClass::Photo => ClassCalib {
            ratio: &PHOTO_RATIO,
            cum: &PHOTO_CUM,
            source_cum: PHOTO_SOURCE_CUM,
        },
        ContentClass::Screen => ClassCalib {
            ratio: &SCREEN_RATIO,
            cum: &SCREEN_CUM,
            source_cum: SCREEN_SOURCE_CUM,
        },
        ContentClass::LineArt => ClassCalib {
            ratio: &LINEART_RATIO,
            cum: &LINEART_CUM,
            source_cum: LINEART_SOURCE_CUM,
        },
        ContentClass::Mixed => ClassCalib {
            ratio: &MIXED_RATIO,
            cum: &MIXED_CUM,
            source_cum: MIXED_SOURCE_CUM,
        },
    }
}

/// A re-encode projection: encode the source at `target_q`, projected to land
/// at `cum` cumulative zensim-A with `size_ratio` of the source size.
#[derive(Debug, Clone, Copy)]
pub struct ReencodeChoice {
    pub target_q: u8,
    pub cum: f32,
    pub size_ratio: f32,
}

/// The source's own cumulative zensim-A vs the original, as a function of
/// effective quality, for `class`. Linear fit `a*q + b`, clamped. Used as the
/// achievable ceiling and the NoOp check.
pub fn source_cum(class: ContentClass, eff_q: f32) -> f32 {
    let (a, b) = calib(class).source_cum;
    (a * eff_q + b).clamp(15.0, 96.0)
}

/// Pick the cheapest re-encode target quality whose projected cumulative meets
/// `target_zensim_a`, for a `class` source of effective quality `eff_q`.
///
/// Interpolates the table rows over `eff_q`, scans target columns, returns the
/// minimum-`size_ratio` column with `cum >= target` and `size_ratio < 1.0`
/// (must actually shrink). `None` if no column both meets the target and
/// shrinks — the router then falls back to a lossless path.
pub fn best_reencode(
    class: ContentClass,
    eff_q: f32,
    target_zensim_a: f32,
) -> Option<ReencodeChoice> {
    let c = calib(class);
    let (lo, hi, frac) = bracket_anchor(eff_q);
    let mut best: Option<ReencodeChoice> = None;
    for (col, &tq) in TARGET_Q_GRID.iter().enumerate() {
        let ratio = lerp(c.ratio[lo][col], c.ratio[hi][col], frac);
        let cum = lerp(c.cum[lo][col], c.cum[hi][col], frac);
        if cum + 1e-3 >= target_zensim_a && ratio < 1.0 {
            let take = match &best {
                None => true,
                Some(b) => ratio < b.size_ratio,
            };
            if take {
                best = Some(ReencodeChoice {
                    target_q: tq,
                    cum,
                    size_ratio: ratio,
                });
            }
        }
    }
    best
}

/// Interpolated cumulative for a `class` source of `eff_q` at table column `col`.
pub fn reencode_cum_at(class: ContentClass, eff_q: f32, col: usize) -> f32 {
    let c = calib(class);
    let col = col.min(TARGET_Q_GRID.len() - 1);
    let (lo, hi, frac) = bracket_anchor(eff_q);
    lerp(c.cum[lo][col], c.cum[hi][col], frac)
}

/// Best achievable cumulative from re-encoding (ignoring the shrink
/// requirement) — used to report the projection even when nothing shrinks.
pub fn max_reencode_cum(class: ContentClass, eff_q: f32) -> f32 {
    let c = calib(class);
    let (lo, hi, frac) = bracket_anchor(eff_q);
    let mut m = 0.0f32;
    for (lo_cum, hi_cum) in c.cum[lo].iter().zip(c.cum[hi].iter()) {
        m = m.max(lerp(*lo_cum, *hi_cum, frac));
    }
    m
}

fn bracket_anchor(eff_q: f32) -> (usize, usize, f32) {
    let last = SOURCE_Q_ANCHORS.len() - 1;
    if eff_q <= SOURCE_Q_ANCHORS[0] {
        return (0, 0, 0.0);
    }
    if eff_q >= SOURCE_Q_ANCHORS[last] {
        return (last, last, 0.0);
    }
    for i in 0..last {
        let a = SOURCE_Q_ANCHORS[i];
        let b = SOURCE_Q_ANCHORS[i + 1];
        if eff_q >= a && eff_q <= b {
            return (i, i + 1, (eff_q - a) / (b - a).max(f32::EPSILON));
        }
    }
    (last, last, 0.0)
}

#[inline]
pub fn lerp(a: f32, b: f32, t: f32) -> f32 {
    a + (b - a) * t
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn source_cum_is_monotone_and_sane() {
        for class in [
            ContentClass::Photo,
            ContentClass::Screen,
            ContentClass::LineArt,
            ContentClass::Mixed,
        ] {
            assert!(
                source_cum(class, 50.0) < source_cum(class, 90.0),
                "{class:?} source_cum not monotone"
            );
            assert!(source_cum(class, 90.0) <= 96.0);
            assert!(source_cum(class, 30.0) >= 15.0);
        }
    }

    #[test]
    fn high_quality_source_recompresses_for_mid_target() {
        // A q90 photo targeting a mid cumulative should find a shrinking re-encode.
        let c = best_reencode(ContentClass::Photo, 90.0, 60.0)
            .expect("q90 photo → 60 should recompress");
        assert!(c.size_ratio < 1.0, "must shrink, got {}", c.size_ratio);
        assert!(c.cum + 1e-3 >= 60.0);
    }

    #[test]
    fn unreachable_target_returns_none() {
        // No class can re-encode a low-q source up to near-lossless.
        assert!(best_reencode(ContentClass::Photo, 50.0, 95.0).is_none());
    }

    #[test]
    fn returned_choice_always_shrinks() {
        for class in [
            ContentClass::Photo,
            ContentClass::Screen,
            ContentClass::LineArt,
            ContentClass::Mixed,
        ] {
            for eq in [30.0, 50.0, 75.0, 90.0] {
                for t in [40.0, 50.0, 60.0, 70.0] {
                    if let Some(c) = best_reencode(class, eq, t) {
                        assert!(
                            c.size_ratio < 1.0,
                            "{class:?} eq{eq} t{t} ratio {}",
                            c.size_ratio
                        );
                        assert!(c.cum + 1e-3 >= t);
                    }
                }
            }
        }
    }

    #[test]
    fn tables_are_well_formed() {
        assert_eq!(SOURCE_Q_ANCHORS.len(), N_ANCHOR);
        assert_eq!(TARGET_Q_GRID.len(), N_TARGET);
    }
}
